# Use postgres/example user/password credentials
version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 25672:5672
      - 15672:15672
